version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 7000:80
    volumes:
      - ./static/conf/nginx-default-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ../mvnproxy-web/dist:/www:ro
    links:
      - mvnproxy

  mvnproxy:
    image: mvnproxy
    volumes:
      - .:/src:ro
    working_dir: /src
    environment:
      PYTHONPATH: .
      SERVER_MODE: production
    command: ["uwsgi", "--thunder-lock",
      "--uid", "101",
      "--gid", "101",
      "--socket", ":7001",
      "--wsgi-file", "application.py"]

